// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO6b0bWedGUUXnuegjD_G18tUlPoZ9wmU',
    appId: '1:1030910227838:web:054ef059d712679a56af2f',
    messagingSenderId: '1030910227838',
    projectId: 'mybeas',
    authDomain: 'mybeas.firebaseapp.com',
    storageBucket: 'mybeas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8YnDAiiLvFS63H7xSy7lWFTGmMqKPePs',
    appId: '1:1030910227838:android:785e34ba4323292456af2f',
    messagingSenderId: '1030910227838',
    projectId: 'mybeas',
    storageBucket: 'mybeas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC60BClGvBrRCbIF_Yt5jwDoGFxXE6abYw',
    appId: '1:1030910227838:ios:c1c7864cf2dea65456af2f',
    messagingSenderId: '1030910227838',
    projectId: 'mybeas',
    storageBucket: 'mybeas.firebasestorage.app',
    iosClientId: '1030910227838-jrg7tl6oaktlrd4mta9e2c2b97hitpib.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication202412200922',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC60BClGvBrRCbIF_Yt5jwDoGFxXE6abYw',
    appId: '1:1030910227838:ios:c1c7864cf2dea65456af2f',
    messagingSenderId: '1030910227838',
    projectId: 'mybeas',
    storageBucket: 'mybeas.firebasestorage.app',
    iosClientId: '1030910227838-jrg7tl6oaktlrd4mta9e2c2b97hitpib.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication202412200922',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO6b0bWedGUUXnuegjD_G18tUlPoZ9wmU',
    appId: '1:1030910227838:web:89ad1cab2ae60b7156af2f',
    messagingSenderId: '1030910227838',
    projectId: 'mybeas',
    authDomain: 'mybeas.firebaseapp.com',
    storageBucket: 'mybeas.firebasestorage.app',
  );

}