// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZU92uQit234hfg0B2orQETJXrOx8zvd8',
    appId: '1:1030910227838:web:a98ee03c06c0e3cb56af2f',
    messagingSenderId: '1030910227838',
    projectId: 'mybeas',
    authDomain: 'mybeas.firebaseapp.com',
    storageBucket: 'mybeas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8YnDAiiLvFS63H7xSy7lWFTGmMqKPePs',
    appId: '1:1030910227838:android:fd013d3595b3627856af2f',
    messagingSenderId: '1030910227838',
    projectId: 'mybeas',
    storageBucket: 'mybeas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC60BClGvBrRCbIF_Yt5jwDoGFxXE6abYw',
    appId: '1:1030910227838:ios:1888d58526782c7656af2f',
    messagingSenderId: '1030910227838',
    projectId: 'mybeas',
    storageBucket: 'mybeas.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication202412130916',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC60BClGvBrRCbIF_Yt5jwDoGFxXE6abYw',
    appId: '1:1030910227838:ios:1888d58526782c7656af2f',
    messagingSenderId: '1030910227838',
    projectId: 'mybeas',
    storageBucket: 'mybeas.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication202412130916',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO6b0bWedGUUXnuegjD_G18tUlPoZ9wmU',
    appId: '1:1030910227838:web:054ef059d712679a56af2f',
    messagingSenderId: '1030910227838',
    projectId: 'mybeas',
    authDomain: 'mybeas.firebaseapp.com',
    storageBucket: 'mybeas.firebasestorage.app',
  );

}